
function drawLine(
  lineLayer,
  a,
  b,
  options = {}
) {
  if (!a || !b) {
    console.warn(
      "Cannot draw line: missing endpoint",
      { a, b }
    );

    return null;
  }

  const line = createSvgElement("line", {
    x1: a.x,
    y1: a.y,
    x2: b.x,
    y2: b.y,

    stroke:
      options.stroke ||
      drawConfig.wireStroke,

    "stroke-width":
      options.strokeWidth ||
      drawConfig.wireStrokeWidth,

    "stroke-linecap": "round",

    class:
      options.className ||
      "edge",
  });

  lineLayer.appendChild(line);

  return line;
}

function drawDot(layer, point, options = {}) {
  const dot = createSvgElement("circle", {
    cx: point.x,
    cy: point.y,
    r: options.radius || drawConfig.nodeRadius,
    fill: options.fill || drawConfig.nodeFill,
    stroke: options.stroke || drawConfig.nodeStroke,
    "stroke-width": 1.5,
  });

  layer.appendChild(dot);
}

function drawLabel(labelLayer, text, x, y, options = {}) {
  if (!text) {
    return;
  }

  const label = createSvgElement("text", {
    x,
    y,
    "text-anchor": options.anchor || "middle",
    "dominant-baseline": "middle",
    "font-family": drawConfig.fontFamily,
    "font-size": options.size || "9px",
    fill: options.fill || "#334155",

    // White outline hides the wire behind the text.
    stroke: options.background || "#ffffff",
    "stroke-width": options.backgroundWidth || 4,
    "paint-order": "stroke",
    "stroke-linejoin": "round",

    class: "net-label",
  });

  label.textContent = text;
  labelLayer.appendChild(label);
}

function drawComponent(
  componentLayer,
  pinStubLayer,
  rawElement
) {
  const element =
    normalizeElement(rawElement);

  const center = element.center;
  const halfImage =
    drawConfig.imageSize / 2;

  // Connect the visible symbol to the larger
  // routing rectangle generated by Python.
  drawLine(
    pinStubLayer,
    element.inputPin,
    {
      x: center.x - halfImage,
      y: center.y,
    }
  );

  drawLine(
    pinStubLayer,
    {
      x: center.x + halfImage,
      y: center.y,
    },
    element.outputPin
  );

  const image = createSvgElement("image", {
    href: element.image,

    x: center.x - halfImage,
    y: center.y - halfImage,

    width: drawConfig.imageSize,
    height: drawConfig.imageSize,

    class: "component-image",
  });

  const componentType =
    Array.isArray(element.type)
      ? element.type[0]
      : element.type;

  if (
    componentType === "R" &&
    drawConfig.rotateResistors
  ) {
    image.setAttribute(
      "transform",
      `rotate(90 ${center.x} ${center.y})`
    );
  }

  const group = createSvgElement("g", {
    class: "component",
    "data-element-id": element.id,
  });

  group.appendChild(image);
  componentLayer.appendChild(group);
}


function drawLayoutCellBoundaries(
  layer,
  layoutCells
) {
  for (const cell of layoutCells || []) {
    const group = createSvgElement("g", {
      class: "layout-cell",
      "data-layout-cell":
        cell.layout_cell || cell.id,
    });

    const rectangle = createSvgElement(
      "rect",
      {
        x: cell.x,
        y: cell.y,
        width: cell.width,
        height: cell.height,

        rx: 16,
        ry: 16,

        fill: "#f8fafc",
        "fill-opacity": "0.7",

        stroke: "#64748b",
        "stroke-width": 2,
        "stroke-dasharray": "10 6",

        class:
          "layout-cell-boundary",
      }
    );

    const title = createSvgElement(
      "text",
      {
        x: Number(cell.x) + 18,
        y: Number(cell.y) + 27,

        "font-family":
          drawConfig.fontFamily,

        "font-size": "16px",
        "font-weight": "700",

        fill: "#0f172a",

        class:
          "layout-cell-title",

        "pointer-events": "none",
      }
    );

    title.textContent =
      cell.layout_cell ||
      cell.id ||
      "Layout cell";

    const details = createSvgElement(
      "text",
      {
        x: Number(cell.x) + 18,
        y: Number(cell.y) + 48,

        "font-family":
          drawConfig.fontFamily,

        "font-size": "11px",

        fill: "#475569",

        class:
          "layout-cell-details",

        "pointer-events": "none",
      }
    );

    const elementCount =
      Array.isArray(cell.elements)
        ? cell.elements.length
        : 0;

    details.textContent =
      `${cell.net_in ?? "none"} → ` +
      `${cell.net_out ?? "none"} | ` +
      `${elementCount} elements`;

    group.appendChild(rectangle);
    group.appendChild(title);
    group.appendChild(details);

    layer.appendChild(group);
  }
}


function drawExternalPorts(
  wireLayer,
  dotLayer,
  labelLayer,
  externalPorts
) {
  for (const port of externalPorts || []) {
    const direction =
      port.pin === "in" ? -1 : 1;

    const start = {
      x: Number(port.x),
      y: Number(port.y),
    };

    const end = {
      x:
        start.x +
        direction *
          drawConfig.externalPortLength,

      y: start.y,
    };

    drawLine(
      wireLayer,
      start,
      end,
      {
        stroke:
          port.net === "GND!"
            ? drawConfig.groundFill
            : drawConfig.wireStroke,

        className:
          "edge external-port",
      }
    );

    drawDot(
      dotLayer,
      end,
      port.net === "GND!"
        ? {
            radius:
              drawConfig.groundRadius,

            fill:
              drawConfig.groundFill,

            stroke:
              drawConfig.groundStroke,
          }
        : {}
    );

    drawLabel(
      labelLayer,
      port.net,

      end.x + direction * 8,
      end.y - 10,

      {
        anchor:
          direction < 0
            ? "end"
            : "start",

        fill:
          port.net === "GND!"
            ? drawConfig.groundFill
            : "#334155",
      }
    );
  }
}

function drawCircuit(data) {
  const board =
    document.getElementById(
      "drawing_board"
    );

  board.innerHTML = "";

  if (
    !data ||
    !data.canvas ||
    !Array.isArray(data.elements) ||
    !Array.isArray(data.layout_cells) ||
    !Array.isArray(data.routes)
  ) {
    board.textContent =
      "Regenerate circuit_data.js with the new Python exporter.";

    return;
  }

  const canvasWidth = Math.max(
    900,
    Number(data.canvas.width)
  );

  const canvasHeight = Math.max(
    550,
    Number(data.canvas.height)
  );

  const svg =
    createSvg(
      canvasWidth,
      canvasHeight
    );

  board.appendChild(svg);

  const layoutCellLayer =
    createSvgElement("g", {
      class: "layout-cell-layer",
    });

  const wireLayer =
    createSvgElement("g", {
      class: "wire-layer",
    });

  const pinStubLayer =
    createSvgElement("g", {
      class: "pin-stub-layer",
    });

  const dotLayer =
    createSvgElement("g", {
      class: "dot-layer",
    });

  const componentLayer =
    createSvgElement("g", {
      class: "component-layer",
    });

  const labelLayer =
    createSvgElement("g", {
      class: "label-layer",
    });

  svg.appendChild(layoutCellLayer);
  svg.appendChild(wireLayer);
  svg.appendChild(pinStubLayer);
  svg.appendChild(dotLayer);
  svg.appendChild(componentLayer);
  svg.appendChild(labelLayer);

  drawLayoutCellBoundaries(
    layoutCellLayer,
    data.layout_cells
  );

  drawGeneratedRoutes(
    wireLayer,
    data.routes
  );

  drawExternalPorts(
    wireLayer,
    dotLayer,
    labelLayer,
    data.external_ports
  );

  for (const element of data.elements) {
    drawComponent(
      componentLayer,
      pinStubLayer,
      element
    );
  }

  if (
    Array.isArray(data.routing_errors) &&
    data.routing_errors.length > 0
  ) {
    console.warn(
      "Python routing errors:",
      data.routing_errors
    );
  }

  setupPanZoom(
    svg,
    canvasWidth,
    canvasHeight
  );
}

function normalizeElement(element) {
  const width = Number(
    element.width ?? drawConfig.imageSize
  );

  const height = Number(
    element.height ?? drawConfig.imageSize
  );

  return {
    ...element,
    width,
    height,

    center: {
      x: Number(element.x) + width / 2,
      y: Number(element.y) + height / 2,
    },

    inputPin: {
      x: Number(element.pins.in.x),
      y: Number(element.pins.in.y),
      net: element.net_in,
    },

    outputPin: {
      x: Number(element.pins.out.x),
      y: Number(element.pins.out.y),
      net: element.net_out,
    },
  };
}

window.addEventListener("DOMContentLoaded", () => {
  const board = document.getElementById("drawing_board");

  if (
    !window.circuitData ||
    !Array.isArray(window.circuitData.elements)
  ) {
    board.textContent =
      "Circuit data is missing. Generate circuit_data.js first.";
    return;
  }

  console.table(
    window.circuitData.elements.map((element, index) => ({
      index,
      id: element.id,
      raw: element.raw,
      path: element.path,
      pid: element.pid,
      layout_cell: element.layout_cell,
      type: element.type,
      net_in: element.net_in,
      net_out: element.net_out,
      image: element.image
    }))
  );
  drawCircuit(window.circuitData);
});
